### ISSUE TITLE
Doesn't recognize the comment in the toml configuration at the top of the file

### ISSUE THREAD

**Issue by BrentHuang** [mjbvz/vscode-github-markdown-preview-style#142]
Doesn't recognize the comment in the toml configuration at the top of the file:

~~~md
+++
title = 'hugo 教程'
date = 2024-08-31T07:55:49+08:00
description = '本文档讲述 hugo 的使用，参考 hugo 官方文档。'
weight = 3
categories = ['站点制作']
tags = ['hugo', 'markdown']
# [params]
#   author = 'John Smith'
+++
~~~

![image](https://github.com/user-attachments/assets/14cccde1-0d3b-4d41-879e-58b3738ea707)

**Comment by mjbvz** [comment]
This doesn't seem supported on Github in my testing. I also didn't see anything in https://docs.github.com/en/contributing/writing-for-github-docs/using-yaml-frontmatter

Maybe it's supported on GitHub pages? But since it doesn't work for normal md files, I think this is out of scope for this extension
