### ISSUE TITLE
Broken Vertical Spacing When Printing To HTML

### ISSUE THREAD

**Issue by cvogt729** [mjbvz/vscode-github-markdown-preview-style#143]
I use the following Markdown extensions in vscode:

- *Markdown Preview Github Styling*
- *Markdown All in One*
- *Markdown Checkboxes*
- *Markdown Emoji*
- *Markdown Footnotes*
- *Markdown yaml Preamble*

My settings relevant to Markdown are:

```json
{
  "markdown.extension.print.absoluteImgPath": false,
  "markdown.extension.print.onFileSave": true,
  "markdown-preview-github-styles.colorTheme": "dark",
  "markdown.extension.print.theme": "dark",
  "markdown.extension.math.enabled": false
}
```

I use the *Markdown All in One* extension primarily to print my Markdown documents to HTML. In version 2.0.4 of *Markdown Preview Github Styling*, all my documents print to HTML as expected as shown in the screenshot below.

![v2 0 4](https://github.com/user-attachments/assets/818d29a3-7c4d-4af9-8586-81169762cb2d)

However, version 2.1.0 of *Markdown Preview Github Styling* seems to have broken this. The same sample document now prints as:

![v2 1 0](https://github.com/user-attachments/assets/bffca40c-be87-4283-bb70-bf60620fed8b)

The raw Markdown of this sample document is:

```markdown
# Wikipedia - Ring

In mathematics, rings are algebraic structures that generalize fields: multiplication need not be commutative and multiplicative inverses need not exist. Informally, a ring is a set equipped with two binary operations satisfying properties analogous to those of addition and multiplication of integers. Ring elements may be numbers such as integers or complex numbers, but they may also be non-numerical objects such as polynomials, square matrices, functions, and power series.

Formally, a ring is a set endowed with two binary operations called addition and multiplication such that the ring is an abelian group with respect to the addition operator, and the multiplication operator is associative, is distributive over the addition operation, and has a multiplicative identity element. (Some authors define rings without requiring a multiplicative identity and instead call the structure defined above a ring with identity. See § Variations on the definition.)

Whether a ring is commutative has profound implications on its behavior. Commutative algebra, the theory of commutative rings, is a major branch of ring theory. Its development has been greatly influenced by problems and ideas of algebraic number theory and algebraic geometry. The simplest commutative rings are those that admit division by non-zero elements; such rings are called fields.
```

For now, my solution is to rollback the extension to version 2.0.4. I looked into the generated HTML, and the correct HTML has some CSS saying `margin-bottom:16px` on relevant pieces of the document, while the incorrect HTML does not include this.

I know interactions between extensions are not necessarily easy to predict, but I was hoping someone could shed some light on this issue. Thank you.

**Comment by jjspace** [comment]
github switched to using more css variables for spacing and padding including that one for paragraphs. The version of [`generate-github-markdown-css`](https://github.com/sindresorhus/generate-github-markdown-css/pull/35) this now uses in `2.1.0` accounts for and relies on those variables. I don't know how Markdown All In One is generating the html and including CSS but it's missing those somehow.

![2024-10-29_13-51](https://github.com/user-attachments/assets/48855f22-c673-4c44-9ce7-163b3c2da9e8)

Probably worth [opening an issue on their side](https://github.com/yzhang-gh/vscode-markdown/issues) given it's dependent on how they handle the html export of css. Might be able to do something to help it on this side but probably need guidance from them since this extension is working correctly in the preview panel.

**Comment by mjbvz** [comment]
Yes I think this will need to be fixed by markdown all in one since it sounds specific to their extension's functionality
